version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:958175408450:task-definition/tweet-app-td:3"
        LoadBalancerInfo:
          ContainerName: "tweet-app-container"
          ContainerPort: "80"
        PlatformVersion: "LATEST"